### ISSUE TITLE
Syntax Highlighting: Unstable Tracking Issue

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust-enhanced#333]
This is a tracking issue for unstable syntax that is currently not supported. I think it is OK to add support for some of these before it is stabilized, as long as the changes aren't too invasive (and can be easily backed out or changed if the feature changes before it is stabilized).  This issue is mainly intended as a heads-up for things on the horizon.

- [ ] 1. Raw identifiers.  [RFC 2151](https://github.com/rust-lang/rfcs/blob/master/text/2151-raw-identifiers.md), on track to stabilize for 2018.
    ```rust
    fn r#match() { }
    ```
- [ ] 2. Crate keyword in path.  [RFC 2126](https://github.com/rust-lang/rfcs/blob/master/text/2126-path-clarity.md), currently up for debate (see issue [53130](https://github.com/rust-lang/rust/issues/53130)).  I think it should be highlighted similar to super/self.
   ```rust
   use crate::foo::bar;
   ```
- [ ] 3. Crate as visibility modifier.  [RFC 2126](https://github.com/rust-lang/rfcs/blob/master/text/2126-path-clarity.md), currently up for debate (see issue [53120](https://github.com/rust-lang/rust/issues/53120)).  Should use `storage.modifier` scope in the `visibility` context.
    ```rust
    crate struct S {}
    ```
- [ ] 4. `vis` macro designator.  [Issue 41022](https://github.com/rust-lang/rust/issues/41022), stabilizing very soon.
    ```rust
     macro_rules! foo{($vis:vis) => () }
    ```
- [ ] 5. Async/await syntax.  [RFC 2394](https://github.com/rust-lang/rfcs/blob/master/text/2394-async_await.md) [issue 50547](https://github.com/rust-lang/rust/issues/50547).  Looks like this is pretty far from being settled.
- [ ] 6. Throw/catch.  [Issue 31436](https://github.com/rust-lang/rust/issues/31436).  Still unsettled.
- [ ] 7. "default" keyword for specialization.  [RFC 1210](https://github.com/rust-lang/rfcs/blob/master/text/1210-impl-specialization.md) [issue 31844](https://github.com/rust-lang/rust/issues/31844).  Still unsettled.
    ```rust
    default fn f() {}
    default impl Trait for X {}
    ```

This list is far from complete, but covers a few things I'm aware of and are under active development.  If anyone knows of something to add, please add a comment.

**Comment by tommit** [comment]
- [ ] 8. Raw reference operator. [RFC 2582](https://github.com/rust-lang/rfcs/blob/master/text/2582-raw-reference-mir-operator.md) [issue 64490](https://github.com/rust-lang/rust/issues/64490)
```rust
let x: i32 = 0;
let _ = &raw const x as *const u32;

let mut y: i32 = 0;
let _ = &raw mut y as *mut u32;
```
